# Buildpacks to include in builder
[[buildpacks]]
id = "sankara/elixir-buildpack:alpine"
version = "0.0.2"
uri = "sankara/elixir-buildpack:alpine"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.3"
  version = "5.6.3"

[[order]]

    [[order.group]]
        id = "sankara/elixir-buildpack:alpine"
        version = "0.0.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.6.3"
	

# Stack that will be used by the builder
[stack]
id = "com.speedyorbit.stacks.elixir"
run-image = "sankara/elixir-stacks-run:elixir"
build-image = "sankara/elixir-stacks-build:elixir"
