# Buildpacks to include in builder
[[buildpacks]]
id = "sankara/elixir-buildpack:alpine"
version = "0.0.2"
uri = "sankara/elixir-buildpack:alpine"

[[order]]
    [[order.group]]
        id = "sankara/elixir-buildpack:alpine"
        version = "0.0.2"

# Stack that will be used by the builder
[stack]
id = "com.speedyorbit.stacks.elixir"
run-image = "sankara/elixir-stacks-run:elixir"
build-image = "sankara/elixir-stacks-build:elixir"
